# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
  
    List.create!(:address => "18 Lathrop St.", :city => "Madison", :state => "Wisconsin", :zip => 53726, :region => 3, :bedrooms => 3, :bathrooms => 1, :rent => 1600, :parking => false, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "20 Lathrop St.", :city => "Madison", :state => "Wisconsin", :zip => 53726, :region => 3, :bedrooms => 3, :bathrooms => 1, :rent => 1600, :parking => false, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "30 Lathrop St.", :city => "Madison", :state => "Wisconsin", :zip => 53726, :region => 3, :bedrooms => 3, :bathrooms => 1, :rent => 1600, :parking => false, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #507", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #204", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #302", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #314", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #803", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #101", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "1022 W Johnson St. #209", :city => "Madison", :state => "Wisconsin", :zip => 53715, :region => 2, :bedrooms => 3, :bathrooms => 2, :rent => 2660, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 10, :gas => true, :garbagecollection => true, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "412 Paunack Pl.", :city => "Madison", :state => "Wisconsin", :zip => 53726, :region => 3, :bedrooms => 3, :bathrooms => 1, :rent => 1400, :parking => true, :smoking => false, :electric => false, :pets => false, :heat => true, :flags => 5, :gas => true, :garbagecollection => false, :ltype => true, :length => 12, :furnished => false, :laundry => false)
    List.create!(:address => "Address3", :city => "Madison", :state => "Wisconsin", :zip => 53706, :region => 1, :bedrooms => 5, :bathrooms => 2, :rent => 2600, :squarefeet => 2000, :parking => true, :smoking => false, :electric => false, :pets => false, :heat => false, :flags => 0, :gas => true, :garbagecollection => true, :ltype => false, :length => 12, :furnished => false, :laundry => true)      
    List.create!(:address => "Address4", :city => "Madison", :state => "Wisconsin", :zip => 53716, :region => 2, :bedrooms => 8, :bathrooms => 6, :rent => 5500, :squarefeet => 5000, :parking => true, :smoking => true, :pets => true, :heat => true, :flags => 0, :gas => false, :garbagecollection => false, :ltype => true, :length => 12, :furnished => false, :laundry => true)
    List.create!(:address => "Address5", :city => "Madison", :state => "Wisconsin", :zip => 53726, :region => 3, :bedrooms => 1, :bathrooms => 1, :rent => 800, :squarefeet => 500, :parking => false, :smoking => false, :pets => false, :electric => false, :heat => false, :flags => 0, :gas => false, :garbagecollection => false, :ltype => false, :length => 12, :furnished => false, :laundry => false)
    List.create!(:address => "Address6", :city => "Madison", :state => "Wisconsin", :zip => 53706, :region => 1, :bedrooms => 2, :bathrooms => 1, :rent => 1200, :squarefeet => 1000, :parking => true, :smoking => false, :pets => false, :heat => false, :flags => 0, :gas => true, :garbagecollection => true, :ltype => false, :length => 12, :furnished => false, :laundry => true)

    
    User.create!(:Name => "Adam", :Email => "aeggum12@gmail.com", :password => "password", :password_confirmation => "password", :admin => true)
    User.create!(:Name => "Admin", :Email => "a@a.com", :password => "password", :password_confirmation => "password", :admin => true)
